### ISSUE TITLE
Animating pages on tapping on navigation pager items

### ISSUE THREAD

**Issue by stanislausakharchukdev** [tzef/BmoViewPager#8]
I have view pager with 2 items. For example, when I move to second item with swipe and then back to first with tapping on it's cell item in view pager navigation bar transition to first page is animating. But when I start to tap on cells items without using swipe gestures pager stops animate page changes. Is there a way to animate page changes in any cases?

**Comment by tzef** [comment]
Hi, there is a property `isInterporationAnimated` in BmoViewPagerNavigationBar, the value default is true, which can let navigation bar moving with animation by tap navigation bar item.

If what you mean is no scroll view animation when tap navigation bar item, that because other childViewController is not in cache of viewPager's UIPageViewController.

Declared two variable for your 2 page view controller, keep the reference, every time when `bmoViewPagerDataSource(_ viewPager: BmoViewPager, viewControllerForPageAt page: Int) -> UIViewController` been called, return the same view controller

**Comment by stanislausakharchukdev** [comment]
How can I add child view controllers to viewPager? Currently I have an array which contains two view controllers (means I have references to them all the time when viewPager is on screen), and in the datasource method you mentioned I return view controller from this array, but there is still no animation in the case I explained above.
So as I understood from your answer I need to somehow set my view controller as child to exactly view pager view controller. How I do that?

**Comment by tzef** [comment]
sorry, it's my fault.
The interpolation is not work for scrollView animation, I have fixed it for new version 4.1.0.
You can see the demo in file DemoViewController1.swift
step 1:
Declared variables for your page view controllers, keep the reference, every time when `bmoViewPagerDataSource(_ viewPager: BmoViewPager, viewControllerForPageAt page: Int) -> UIViewController` been called, return the same view controller
step 2:
call `public func setReferencePageViewController(_ vc: UIViewController, at page: Int)` after the page view controllers ready
Hope it will help for you

**Comment by stanislausakharchukdev** [comment]
Thanks a lot man but now I have following problem: what was working previous version is not working now.
Here is the code of data source method.
func bmoViewPagerDataSource(_ viewPager: BmoViewPager, viewControllerForPageAt page: Int) -> UIViewController {
        configure(mapViewController: mapViewControllerTest)
        switch page {
        case 0:
            FlurryEvent.shared.logEvent(event: .allEvents)
            mapViewControllerTest.eventMembersType = .all
        case 1:
            FlurryEvent.shared.logEvent(event: .coupleEvents)
            mapViewControllerTest.eventMembersType = .double
        case 2:
            FlurryEvent.shared.logEvent(event: .groupEvents)
            mapViewControllerTest.eventMembersType = .group
        case 3:
            FlurryEvent.shared.logEvent(event: .myEvents)
            mapViewControllerTest.eventMembersType = .single
        default:
            break
        }
        return mapViewControllerTest
    }
I create this mapViewController variable in my controller which hold view pager, then I'm just returning this property in datasource method, but before I'm setting type variable which has didSet logic inside.
So for now behavior is strange, when I just tap cells one by one and moving forward to everything is ok, but when I try to move back to any section looks like view pager just reloads the initial view controller but it supposed to just return existing with new property set. Last version i used (4.0.5) everything was ok.

**Comment by tzef** [comment]
Hi, you return the same view controller in different pages? 
I think you need to initial unique UIViewController for every page.

Because `BmoViewPager` is based on `UIPageViewController`, and when the scroll view scroll to edge, it will call the `func pageViewController(_ pageViewController: UIPageViewController, viewControllerAfter viewController: UIViewController) -> UIViewController?` and `func pageViewController(_ pageViewController: UIPageViewController, viewControllerBefore viewController: UIViewController) -> UIViewController?` to get next and previous page.

At the same time I save the view controller and page number in the view controller's view, it will let the this page view controller has wrong property.
