### ISSUE TITLE
scrollable has no effect

### ISSUE THREAD

**Issue by ThomGru** [tzef/BmoViewPager#9]
The property `scrollable` on the `BmoViewPager` seems to have no effect. 

I want to prevent the user to swipe left and right to change the content. That should be possible only with the `BmoViewPagerNavigationBar`

Any hints?

**Comment by tzef** [comment]
You set viewPager.scrollable = false, but it still can scroll ?
It sounds amazing...because the property directly set the UIPageViewController UIScrollView's `isScrollEnabled`
Can you check the scrollView's isScrollEnabled is false or not ?
you can get the scrollView by this way
`(theViewPager.subviews[0].subviews[0] as? UIScrollView)?.isScrollEnabled`

**Comment by ThomGru** [comment]
Right after I set the `scrollable` property of the `BmoViewPager` to `false`, `isScrollEnabled` of the `UIScrollView` is `false` too. So far so good.
 But if I check again later (lets say in one of the delegate methods) this property becomes `true`.

**Comment by tzef** [comment]
Thanks for your report, it's really a bug, it will happen when you reload the viewPager.
I found that the scrollView of UIPageViewController will reset the isScrollEnabled to true after set the dataSource, so I set the property again after UIPageViewController reset.
The fix updated at version 4.1.1

**Comment by ThomGru** [comment]
It is working now. Thanks for your support. 

I worked around this bug by setting the `scrollable` property of the viewPager `BmoViewPager` to false in the delegate function `bmoViewPagerDataSource(_ viewPager: BmoViewPager, viewControllerForPageAt page: Int) -> UIViewController` but can remove it now. 

Ticket could be closed now. Thanks again.
